global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'sentiment-app'
    static_configs:
      - targets: ['ml-app:7860']
        labels:
          service: 'sentiment-ml-app'
          
  - job_name: 'chroma-db'
    static_configs:
      - targets: ['chroma-db:8000']
        labels:
          service: 'chroma-vector-db'